/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2022-06-07 19:17:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class clouse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h1>약관동의</h1>\r\n");
      out.write("\t\t<form action=\"writeForm.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label> 회원약관 </label>\r\n");
      out.write("\t\t\t\t<textarea rows=\"10\" class=\"form-control\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t회원약관 회원 약관에는 회원이 꼭 알아두어야 할 회사와 회원의 관계에 대한 중요한 내용이 포함되어 있습니다. 가입을 원하시면\r\n");
      out.write("\t\t\t아래의 회원 약관을 반드시 읽고 동의 버튼을 눌러주세요. 제1장 총칙 제1조 (목적) 이 약관은 전기통신사업법령 및\r\n");
      out.write("\t\t\t정보통신망이용촉진 및 정보보호 등에 관한 법률에 따라 한겨레신문㈜ 및 관계사{씨네21 ㈜(이상, 자회사)\r\n");
      out.write("\t\t\t㈜한겨레플러스(이상, 제휴사)} (이하 `회사`)에서 제공하는 모든 서비스(이하 `서비스`)의 이용절차,조건등 서비스 이용과\r\n");
      out.write("\t\t\t관련한 회사와 회원의 권리 및 의무에 관련된 사항을 규정함을 목적으로 합니다. 제2조 (약관의 효력과 변경) 1.본 약관은\r\n");
      out.write("\t\t\t회원이 신규 가입 시 \"약관에 동의합니다\"라는 물음에 회원이 \"동의\" 버튼을 클릭 하는 것으로 효력이 발생됩니다. 2.회사는\r\n");
      out.write("\t\t\t필요한 경우 약관을 변경할 수 있으며, 변경된 약관은 적용일 전 7일간 온라인 상의 공지나 전자 우편 등의 방법을 통해\r\n");
      out.write("\t\t\t회원에게 공지되고 적용일에 효력이 발생됩니다. 3.회원은 변경된 약관에 동의하지 않을 경우, 서비스 이용을 중단하고 탈퇴할\r\n");
      out.write("\t\t\t수 있습니다. 4.약관이 변경된 이후에도 계속적으로 서비스를 이용하는 경우에는 회원이 약관의 변경 사항에 동의한 것으로\r\n");
      out.write("\t\t\t봅니다. 제3조 (약관 외 준칙) 1.이 약관에 명시되지 않은 사항이 전기통신기본법, 전기통신사업법, 기타 관계법령에 규정\r\n");
      out.write("\t\t\t되어 있을 경우에는 그 규정에 따릅니다. 2.회사는 약관 이외에 개별 서비스에 대한 세부적인 사항을 정할 수 있으며, 그\r\n");
      out.write("\t\t\t내용은 해당 서비스의 이용안내 및 별도의 이용 동의 절차를 통해 공지합니다. 제2장 회원 가입과 서비스 이용 제4조\r\n");
      out.write("\t\t\t(이용계약) 서비스 이용계약은 회원이 회사가 정한 약관에 동의하고, 회사에 가입 및 서비스 이용을 신청하며, 회사가 이를\r\n");
      out.write("\t\t\t허락하는 것 으로 이루어집니다. 제5조 (이용신청) 1.본 서비스를 이용하기 위해서는 회사가 정한 소정의 가입신청서에\r\n");
      out.write("\t\t\t이용자의 정보를 기록해야 합니다. 2.가입신청 양식에 기재된 모든 이용자 정보는 반드시 실제 정보와 동일해야 합니다. 실제\r\n");
      out.write("\t\t\t정보를 입력하지 않거나 사실과 다른 정보를 입력한 사용자는 법적인 보호를 받을 수 없습니다. 제6조 (이용신청의 승낙)\r\n");
      out.write("\t\t\t1.회사는 회원이 모든 사항을 정확히 기재하여 신청할 경우 서비스 이용을 승낙합니다. 단, 아래의 경우는 승낙을 거부하거나\r\n");
      out.write("\t\t\t취소할 수 있습니다. a .실명이 아닌 경우 b .본인의 주민등록번호가 아닌 경우 c .이용신청 시 필요내용을 허위로\r\n");
      out.write("\t\t\t기재하여 신청한 경우 d .사회의 안녕 질서 또는 미풍양속을 저해할 목적으로 신청한 경우 e .전기통신기본법,\r\n");
      out.write("\t\t\t전기통신사업법, 정보통신 윤리강령, 정보통신 윤리위원회 심의규정, 프로그램 보호법 및 기타관련 법령과 약관이 금지하는 행위를\r\n");
      out.write("\t\t\t한 경우 f .마호에 해당하는 사유로 형사처벌을 받은 경우 g .마호에 해당하는 사유로 다른 서비스제공회사로부터 서비스\r\n");
      out.write("\t\t\t이용이 거절된 경력이 있는 경우 h .기타 회사가 정한 이용신청 요건에 맞지 않을 경우 i .만14세 미만의 아동이 부모\r\n");
      out.write("\t\t\t등의 법정대리인의 동의를 얻지 않은 경우 2.회사는 기술적인 이유나 정책 등의 이유로 인해 이용신청의 승낙을 보류할 수\r\n");
      out.write("\t\t\t있습니다. 3.회사는 회원 가입을 위하여 필요한 정보를 요구할 수 있으며, 회원가입 이후에도 추가정보의 입력을 요구할 수\r\n");
      out.write("\t\t\t있습니다. 회원가입 시 요구하는 구체적인 정보는 개인정보 취급방침에서 확인하실 수 있습니다. 4.회사는 회원이 온/오프라인\r\n");
      out.write("\t\t\t이벤트에 참여하거나, 상품 구매시에 제출 또는 취득한 개인정보를 보유할 수 있으며, 동 정보를 회원이 가입시 입력한 회원의\r\n");
      out.write("\t\t\t정보에 추가 또는 수정할 수 있습니다. 5.4 항의 내용에 따라 추가 또는 수정하여 보유할 수 있는 개인정보는 다음과\r\n");
      out.write("\t\t\t같습니다. 전자우편주소, 우편번호, 주소, 전화번호, 이동전화번호, 이벤트 응모일, 상품 구매일, 상품 구매내역, 자동차보험\r\n");
      out.write("\t\t\t만기일 제7조 (회원 아이디 관리) 1.회원의 아이디와 비밀번호에 관한 모든 관리책임은 회원에게 있습니다. 2.회원이 등록한\r\n");
      out.write("\t\t\t아이디 및 비밀번호에 의하여 발생되는 사용상의 과실 또는 제 3자에 의한 부정사용 등에 대한 모든 책임은 해당 회원에게\r\n");
      out.write("\t\t\t있습니다. 제8조 (계약 사항의 변경) 회원은 서비스이용 신청 시 기재한 사항이 변경되었을 경우, 즉시 수정하여야 합니다.\r\n");
      out.write("\t\t\t제3장 개인 정보의 보호 및 이용 제9조 (개인정보 취급방침) 1.회사는 회원의 개인정보를 보호하며, 회사는 그 내용을\r\n");
      out.write("\t\t\t회사의 각 서비스의 메인화면 과 개인정보관리 페이지에 '개인정보 취급방침'이란 이름으로 공지합니다. a .개인정보\r\n");
      out.write("\t\t\t취급방침'에서 언급하고 있는 주요 내용은 다음과 같습니다. b .개인정보관리책임자의 성명/소속부서/지위/전화번호/전자우편\r\n");
      out.write("\t\t\t주소 c .개인정보의 구체적인 수집목적 및 이용목적 d .동의 철회, 열람 또는 정정 요구 등 이용자의 권리와 그 행사방법\r\n");
      out.write("\t\t\te .서비스제공자가 수집하고자 하는 개인정보항목 f .수집하는 개인정보의 보유·이용기간 및 보유이유 g .기타 개인정보에\r\n");
      out.write("\t\t\t대한 가공 또는 관리 방식 h .쿠키의 운영에 관한 사항 i .개인정보 관련 불만처리에 관한 사항 j .개인정보의\r\n");
      out.write("\t\t\t가공목적·가공방식, 가공된 개인정보의 이용·관리 등에 관한 사항 k .개인정보 위탁업체 및 위탁업체에 제공하는 정보 l\r\n");
      out.write("\t\t\t.기타 개인정보의 보호를 위하여 필요한 사항 2.회사는 '개인정보 취급방침'의 내용이 수정, 변경될 경우 변경 이전에 그\r\n");
      out.write("\t\t\t내용을 인터넷홈페이지, 전자우편 등의 방법을 통해 공지합니다. 제10조 (개인정보의 이용) 1.회사는 회원의 동의를 받아\r\n");
      out.write("\t\t\t회원이 회원가입 시 제출한 개인정보를 상호 공유할 수 있습니다. 2.회사는 약관 개정일 이전에 가입한 한겨레신문㈜ 및\r\n");
      out.write("\t\t\t㈜한겨레플러스 회원의 동의를 받아 회원의 개인정보를 공유할 수 있습니다. 3.회사는 회사와 제휴를 맺은 사이트와 회사의\r\n");
      out.write("\t\t\t사이트를 편리하게 이용할 수 있도록 하기 위해 회원의 동의를 받아 회원의 정보를 제휴 사이트들과 공유할 수 있으며, 공유를\r\n");
      out.write("\t\t\t위해 회원의 컴퓨터에 쿠키를 전송할 수 있습니다. 4.회사는 서비스 제공으로 알게 된 회원의 신상정보를 본인의 동의 없이\r\n");
      out.write("\t\t\t제3자에게 누설, 배포하지 않습니다. 단, 다음 각 호에 해당하는 경우에는 예외로 합니다. a .금융실명거래 및 비밀보장에\r\n");
      out.write("\t\t\t관한 법률, 신용정보의 이용 및 보호에 관한 법률,전기통신기본법, 전기통신 사업법, 지방세법, 소비자보호법,한국은행법,\r\n");
      out.write("\t\t\t형사소송법 등 법령에 특별한 규정이 있는 경우 b .통계작성/학술연구 또는 시장조사를 위하여 필요한 경우로서 특정 개인을\r\n");
      out.write("\t\t\t식별할 수 없는 형태로 제공하는 경우 5.회사는 회원의 전체 또는 일부 정보를 업무와 관련된 통계 자료로 사용할 수\r\n");
      out.write("\t\t\t있습니다. 6.회사는 회사의 사업 내용을 회원에게 전화 혹은 전자우편, 우편물 발송, 휴대폰 단문 메시지 전송 등의 방법으로\r\n");
      out.write("\t\t\t홍보하고 상품 구입 및 가입을 권유할 수 있습니다. 7.회사는 양질의 서비스를 제공하기 위해 여러 비즈니스 파트너와 제휴를\r\n");
      out.write("\t\t\t맺어 회원정보를 위탁관리 하게 할 수 있습니다. 그럴 경우 회사는 약관에 위탁관리 업체명 및 목적, 내용을 밝혀 회원의\r\n");
      out.write("\t\t\t동의를 받습니다. 자세한 개인정보 위탁관리 업체는 개인정보 취급방침에서 확인하실 수 있습니다. 8.회원의 개인정보 이용에\r\n");
      out.write("\t\t\t대한 동의는 회원이 본 약관에 동의(2조4항에따른 동의로 보는 경우 포함)하는 것으로서 갈음합니다 \r\n");
      out.write("\t\t\t</textarea>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class = \"form-group\">\r\n");
      out.write("\t\t\t<!-- lavel안에 input tag를 넣으면 박스 뿐 아니라 글자 클릭해도 동작한다. -->\r\n");
      out.write("\t\t\t\t<label><input type = \"checkbox\" required = \"required\" title= \"약관 동의해야 회원가입 가능\" >약관에 동의합니다.</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<button class  =\"btn btn-default\">가입하러 가기</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
