/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2022-06-07 19:16:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class writeForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"#idCheckBtn\").click(\r\n");
      out.write("\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t//window.open = window객체로 창을 여는 메서드\r\n");
      out.write("\t\t\t\t\t//open(url, name, option)\r\n");
      out.write("\t\t\t\t\twindow.open(\"idCheck.jsp\", \"idCheck\",\r\n");
      out.write("\t\t\t\t\t\t\t\"width = 400 ,height = 400, top =100, left=400\")\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h1>회원가입</h1>\r\n");
      out.write("\t\t<!-- 아이디 , 비밀번호, 이름, 성별, 생년월일, 연락처, 이메일, 사진(나중에) -->\r\n");
      out.write("\t\t<!-- 사진 파일을 업로드 하기 위해서 method = \"post\", enctype = \"multipart/form-data\"속성 지정 -->\r\n");
      out.write("\t\t<form action=\"write.jsp\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<!-- div 클래스 분할  tag: 특정한 영역을 지정한다.-->\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<label for=\"id\">아이디</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<input name=\"id\" id=\"id\" required=\"required\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\treadonly=\"readonly\" placeholder=\"아이디 중복체크를 이용하세요. 팝업을 허용하셔야 합니다.\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group-btn\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" id=\"idCheckBtn\" class=\"btn btn-default\">아이디\r\n");
      out.write("\t\t\t\t\t\t\t중복체크</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label for=\"id\">아이디</label> <input name=\"id\" id=\"id\"\r\n");
      out.write("\t\t\t\t\trequired=\"required\" class=\"form-control\" readonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"아이디 중복체크 하세요\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group-btn\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" id=\"idCheckBtn\" class=\"btn btn-default\">아이디\r\n");
      out.write("\t\t\t\t\t\t중복체크</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<label for=\"pw\">비밀번호</label> <input name=\"pw\" type=\"password\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"pw\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<label for=\"pw2\">비밀번호 확인</label> <input type=\"password\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"pw2\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<label for=\"name\">이름</label> <input name=\"name\" type=\"text\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"name\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<label>성별</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-inline\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- style - margin : 바깥쪽 여백 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\" style=\"margin: 0 10px\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<label> <input name=\"gender\" type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" id=\"gender_man\" value=\"남자\" checked=\"checked\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t남자\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<label> <input name=\"gender\" type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" id=\"gender_woman\" value=\"여자\"> 여자\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<label for=\"birth\">생년월일</label> <input name=\"birth\" type=\"date\"\r\n");
      out.write("\t\t\t\t\tclass=\"for-control\" id=\"birth\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<label>연락처</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-inline\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<input name=\"tel\" class=\"form-control\" style=\"width: 60px\"\r\n");
      out.write("\t\t\t\t\t\ttype=\"text\" maxlength=\"3\" pattern=\"[0-9]{2,3}\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"숫자 2 ~ 3자리를 입력할 수 있습니다.\">- <input name=\"tel\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" style=\"width: 80px\" type=\"text\" maxlength=\"4\"\r\n");
      out.write("\t\t\t\t\t\tpattern=\"[0-9]{4}\" title=\"숫자 4자리를 입력할 수 있습니다.\">- <input\r\n");
      out.write("\t\t\t\t\t\tname=\"tel\" class=\"form-control\" style=\"width: 80px\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tmaxlength=\"4\" pattern=\"[0-9]{4}\" title=\"숫자 4자리를 입력할 수 있습니다.\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<label for=\"email\">이메일</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- type : email - 모바일의 키패드가 email입력 패드로 바뀐다. 입력한 데이터가 이메일 양식에 맞는지 검사한다. -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<input name=\"email\" class=\"form-control\" type=\"email\" id=\"email\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<label for=\"photo\">사진</label> <input name=\"photo\" type=\"file\"\r\n");
      out.write("\t\t\t\t\tid=\"photo\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button class=\"btn btn-default\">가입</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button class=\"btn btn-default\" type=\"reset\">새로고침</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button class=\"btn btn-default\" type=\"button\" id=\"cancelBtn\">취소</button>\r\n");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
